name: Java CI with Gradle

on:
  push:
    branches:
      - master
  workflow_dispatch:

  env:
    S3_BUCKET_NAME: freelec-springboot-hwi-build
    PROJECT_NAME: springboot2-webservice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3     # 프로젝트 코드 checkout

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/*
          retention-days: 1

      - name: Make zip file
          run: zip -r ./$GITHUB_SHA.zip .
          shell: bash

      - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region : ap-northeast-2

      - name: Upload to s3
          run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
